### ISSUE TITLE
Ship v0.1.5

### ISSUE THREAD

**Issue by KengoTODA** [KengoTODA/errorprone-slf4j#140]
To release the change introduced by #137, ship a new patch release as soon as possible.

**Comment by KengoTODA** [comment]
`mvn -P release clean verify` fails because javadoc compilation fails due to module not found error like below:

> [ERROR] /Users/kengo/GitHub/errorprone-slf4j/src/main/java/jp/skypencil/errorprone/slf4j/PlaceholderMismatch.java:[9,28] error: package com.google.errorprone.bugpatterns is not visible

**Comment by tbroyer** [comment]
The `--add-exports` and `--add-opens` possibly need to be passed to the `javadoc` executable through `-J--add-exports` in `<additionalJOptions>`.

**Comment by tbroyer** [comment]
Just tried locally, this patch allows javadoc creation (I copy/pasted the `<arg>` lines from the maven-compiler-plugin):
```diff
@@ -190,10 +190,22 @@
                 </goals>
               </execution>
             </executions>
             <configuration>
               <doclint>none</doclint>
+              <additionalJOptions>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
+                <arg>--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
+              </additionalJOptions>
             </configuration>
           </plugin>
           <plugin>
             <groupId>org.apache.maven.plugins</groupId>
             <artifactId>maven-source-plugin</artifactId>
```

**Comment by KengoTODA** [comment]
@tbroyer it worked, thanks!

**Comment by KengoTODA** [comment]
Successfully released new version with the suggested change as #137. Thanks for your support @tbroyer!

* https://github.com/KengoTODA/errorprone-slf4j/releases/tag/v0.1.5
* https://repo1.maven.org/maven2/jp/skypencil/errorprone/slf4j/errorprone-slf4j/0.1.5/
