### ISSUE TITLE
Version 0.1.5 is broken due to incorrect auto-value configuration

### ISSUE THREAD

**Issue by remal** [KengoTODA/errorprone-slf4j#147]
I'm trying to set up errorprone-slf4j v0.1.5 and ErrorProne doesn't discover its checks.

As I can see in the commit https://github.com/KengoTODA/errorprone-slf4j/commit/c4b9ea29dfaa8f18a5a4e45f4c42e0da241a4a30 this was added to pom.xml: https://github.com/KengoTODA/errorprone-slf4j/blob/c4b9ea29dfaa8f18a5a4e45f4c42e0da241a4a30/pom.xml#L76-L82

By adding this, `com.google.auto.service:auto-service` annotation processor became disabled.

As you can see, in [the created JAR file](https://repo1.maven.org/maven2/jp/skypencil/errorprone/slf4j/errorprone-slf4j/0.1.5/errorprone-slf4j-0.1.5.jar), there is no `META-INF/services/` file. That's why ErrorProne can find checks of errorprone-slf4j.

The issue can be fixed, by adding this dependency into `annotationProcessorPaths`: https://github.com/KengoTODA/errorprone-slf4j/blob/c4b9ea29dfaa8f18a5a4e45f4c42e0da241a4a30/pom.xml#L111-L113

**Comment by KengoTODA** [comment]
Confirmed that the latest `master` branch 2d8197e2a2afdd85152d8ae6734bb01f7fef1854 does not have this problem:

```
   creating: META-INF/services/
  inflating: META-INF/services/com.google.errorprone.bugpatterns.BugChecker  
```

It is because I've replaced the build tool from Maven to Gradle, and in its procedure I've fixed it unintentionally. I will ship 0.1.6 later. Thanks for your notice!

**Comment by KengoTODA** [comment]
v0.1.6 is now ready on Maven Central. Thanks again for your report @remal!
https://repo1.maven.org/maven2/jp/skypencil/errorprone/slf4j/errorprone-slf4j/0.1.6/
