### ISSUE TITLE
slf4j:errorprone-slf4j-0.1.7 missing on Maven Central

### ISSUE THREAD

**Issue by joschi** [KengoTODA/errorprone-slf4j#165]
It looks like [`jp.skypencil.errorprone.slf4j:errorprone-slf4j:0.1.7`](https://github.com/KengoTODA/errorprone-slf4j/releases/tag/v0.1.7) never made it to Maven Central:
https://search.maven.org/artifact/jp.skypencil.errorprone.slf4j/errorprone-slf4j and https://repo1.maven.org/maven2/jp/skypencil/errorprone/slf4j/errorprone-slf4j/ are only listing versions up to [`jp.skypencil.errorprone.slf4j:errorprone-slf4j:0.1.6`](https://search.maven.org/artifact/jp.skypencil.errorprone.slf4j/errorprone-slf4j/0.1.6/jar).

<img width="1081" alt="search.maven.org listing for versions of jp.skypencil.errorprone.slf4j:errorprone-slf4j" src="https://user-images.githubusercontent.com/43951/158650212-1e26a401-f7a2-4b3c-ba43-fad89c7deeca.png">

**Comment by KengoTODA** [comment]
Thanks, I've redeployed artifacts and now it's available at:
https://repo1.maven.org/maven2/jp/skypencil/errorprone/slf4j/errorprone-slf4j/0.1.7/

Seems that I forgot to close & release packages at [OSS Sonatype Nexus](https://oss.sonatype.org/). I will introduce https://github.com/gradle-nexus/publish-plugin/ to reduce the risk.
