### ISSUE TITLE
Fails without details

### ISSUE THREAD

**Issue by php-coder** [KengoTODA/errorprone-slf4j#22]
I tried to add this plugin but it fails without obvious reason:
```
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ mystamps ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 313 source files to /Users/coder/git/mystamps.git/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

The error reporting could be more helpful. At this moment, I don't know how to fix this, so it seems that it's a bug in the plugin itself.

**Comment by KengoTODA** [comment]
Thanks for your share! To fix this issue, could you try to:

1. run your maven with debug mode (`--debug`) to get more info,
2. make a [mcve](https://stackoverflow.com/help/mcve) project reproducing your problem, or tell me in [which your branch](https://github.com/php-coder/mystamps/branches) I can reproduce, and
3. share which version you're using about javac, errorprone and this errorprone-slf4j

**Comment by php-coder** [comment]
> run your maven with debug mode (--debug) to get more info,

Here is the output: https://gist.github.com/php-coder/919b0a5f578e013a942395c8cf47ce07

> make a mcve project reproducing your problem, or tell me in which your branch I can reproduce, and

I've created `re_error_prone_bug` branch for that.

> share which version you're using about javac, errorprone and this errorprone-slf4j

- javac 1.8.0_45
- errorprone 2.3.2
- errorprone-javac 9+181-r4173-1
- errorprone-slf4j 0.1.3

**Comment by KengoTODA** [comment]
Thanks, I've successfully reproduced this issue in my local! I will investigate this.

**Comment by php-coder** [comment]
Any updates on this?

**Comment by KengoTODA** [comment]
no update, I cannot understand why this happens.

**Comment by KengoTODA** [comment]
I found that errorprone-slf4j v0.1.5 can run `mvn clean compile` as expected on the `re_error_prone_bug` branch. I guess that #137 solved something related this error, but still not so sure why.
