### ISSUE TITLE
False positives in Slf4jPlaceholderMismatch with Throwables

### ISSUE THREAD

**Issue by bsfarrell** [KengoTODA/errorprone-slf4j#45]
```java
logger.info("Found an exception for {}: {}", someObject, someThrowable); // False positive
logger.info("Found an exception for {}:", someObject, someThrowable);
```
The first line is caught by Slf4jPlaceholderMismatch.  I think it's a valid usage- sometimes the first line is preferred over the second if we don't want to actually log the stack trace of the exception.

Of course one way around this would be to do this:
```java
logger.info("Found an exception for {}: {}", someObject, someThrowable.toString());
```
but there are other static analysis checks that will flag code that calls toString() on a parameter.

I think that if the message string has a placeholder for a Throwable, it's best to assume the developer intended to log the string representation of the Throwable, and this shouldn't be caught by Slf4jPlaceholderMismatch.

**Comment by KengoTODA** [comment]
I'm quite not sure when you want to use the 1st line. What is the motivation? Can't you cover your motivation by the configuration of logging framework?

**Comment by bsfarrell** [comment]
The idea is that a codebase will have a mix of both 1 and 2.  There might be specific cases where we don’t want to log a stack trace- for example, if an exception is a common case and we don’t want to pollute the logs with a bunch of stack traces.

**Comment by bsfarrell** [comment]
I suppose this functionality could also be configurable?  I’m happy to submit a PR if you’d like.

**Comment by KengoTODA** [comment]
Well I think what you need is configuration for logging framework, such as [the layout of Logback](https://logback.qos.ch/manual/layouts.html). It's better to keep code common and portable, then use configuration to handle specific cases.

Of course your PR is welcome, but I cannot imagine how we can fulfill both of conflicted demands in one API for now.

**Comment by KengoTODA** [comment]
I'll close this stale issue. Feel free to create a PR to resolve it.
